version: "3.5"

services:
  # Jellyfin
  jellyfin:
    image: jellyfin
    container_name: jellyfin
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - ./data/media:/media
    ports:
      - "8080:8096"
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    env_file:
      - "./.env"