apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: production
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
     app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: {{ .Values.dockerImage }}
        ports:
          - name: http
            containerPort: 8096
            protocol: TCP
        volumeMounts:
        {{- range $.Values.volumes }}
          - name: {{ .name }}
            mountPath: {{ .containerPath }}
        {{- end }}
      volumes:
      {{- range $.Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
      {{- end }}