apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: {{ .Values.namespace }}
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
     app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: {{ .Values.dockerImage }}
        ports:
          - name: http
            containerPort: 8096
            protocol: TCP
        volumeMounts:
        {{- range $i, $volume := .Values.volumes }}
          - name: {{ $volume.name }}
            mountPath: {{ $volume.containerPath }}
        {{- end }}
      volumes:
      {{- range $i, $volume := .Values.volumes }}
        - name: {{ $volume.name }}
          persistentVolumeClaim:
            claimName: {{ $volume.name }}
      {{- end }}