{{- range $i, $volume := .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $volume.name }}
  namespace: {{ $.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ $volume.localNodePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ $volume.nodeSelectorHostName}}
---
{{- end }}