{{- range $.Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  namespace: production
spec:
  capacity:
    storage: {{ .storageCapacity }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: {{ .localNodePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .nodeSelectorHostName }}
---
{{- end }}