apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
  namespace: production
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /pixelpiloten/k3s/jellyfin/data/cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dreadnaught