kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-cache
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi