apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: jellyfin
  ports:
    - port: 80
      targetPort: 8096
      protocol: TCP
      name: http